name: lifeos_client
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  desktop_multi_window: ^0.2.0
  drift: any
  web_socket_channel: ^3.0.3
  path_provider: ^2.1.5
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  drift_dev: any

flutter:
  uses-material-design: true
