import 'package:drift/drift.dart';
import 'database.dart';
import 'tables.dart';

part 'dao.g.dart'; // generated by drift builder

@DriftAccessor(tables: [LifeEntities])
class LifeEntitiesDao extends DatabaseAccessor<AppDatabase> with _$LifeEntitiesDaoMixin {
  LifeEntitiesDao(AppDatabase db) : super(db);

  // Reactive query omitting soft-deleted records
  Stream<List<LifeEntity>> watchActiveEntities() {
    return (select(lifeEntities)..where((t) => t.isDeleted.equals(0))).watch();
  }

  // Atomic insert or replace on primary key conflict
  Future<void> insertOrUpdate(Insertable<LifeEntity> entity) {
    return into(lifeEntities).insertOnConflictUpdate(entity);
  }

  // Perform soft delete, marking as dirty for sync_queue interceptor
  Future<void> softDelete(String id, int currentEpochMs) {
    return (update(lifeEntities)..where((t) => t.id.equals(id))).write(
      LifeEntitiesCompanion(
        isDeleted: const Value(1),
        updatedAt: Value(currentEpochMs),
        syncedAt: const Value.absent(), // Explicitly mark as unsynced
      ),
    );
  }
}
