import 'package:drift/drift.dart';
import 'tables.dart';
import 'dao.dart';
import 'markdown_dao.dart';
import 'accounting_dao.dart';
import 'banking_dao.dart';
import 'chtm_dao.dart';
import 'cloud_dao.dart';
import 'darkweb_dao.dart';
import 'flashcards_dao.dart';
import 'home_management_dao.dart';
import 'home_screen_dao.dart';
import 'knowledge_base_dao.dart';
import 'maps_dao.dart';
import 'movies_dao.dart';
import 'music_dao.dart';
import 'gallery_dao.dart';
import 'points_dao.dart';
import 'system_dao.dart';
import 'infinity_dao.dart';
import 'vm_dao.dart';
import 'youtube_dao.dart';

part 'database.g.dart'; // generated by drift builder

class HabitData {
  final String id;
  final String name;
  final bool isCompleted;

  HabitData({
    required this.id,
    required this.name,
    required this.isCompleted,
  });

  factory HabitData.fromMap(Map<String, dynamic> map) {
    return HabitData(
      id: map['id'] as String? ?? '',
      name: map['name'] as String? ?? '',
      isCompleted: map['done'] == 1,
    );
  }
}

@DriftDatabase(
  tables: [
    LifeEntities, SyncQueue, SystemSettings, UserProfiles, MarkdownNotes, NotesIndices, 
    AccountingCredentials, AccountingDocuments, BankAccounts, BankLedgers, BillLogs, BankingRollovers,
    Books, Audiobooks, ReadingProgress, BookHighlights,
    CalendarEvents, UserTasks, UserHabits, HabitLogs,
    DeviceBackups, BackupLogs, UploadQuarantines,
    Torrents, TorrentPeers, SharedFiles,
    FlashcardDecks, Flashcards, FlashcardReviews,
    SmartDevices, EnvironmentLogs, DeviceSchedules,
    SystemUsers, LocalNotifications,
    KnowledgeTopics, KnowledgeRelationships,
    Geofences, LocationLogs, Bookmarks,
    Movies, MovieWatchlists, MovieReviews,
    MusicTracks, Playlists, PlaylistTracks,
    MediaAssets, MediaTags,
    PointRules, PointsLedgers, Vouchers,
    DailyWords, DailyTrivias,
    VirtualMachines, RemoteSessions,
    YoutubeSessions, YoutubeDownloads
  ],
  daos: [LifeEntitiesDao, MarkdownDao, AccountingDao, BankingDao, ChtmDao, CloudDao, DarkWebDao, FlashcardsDao, HomeManagementDao, HomeScreenDao, KnowledgeBaseDao, MapsDao, MoviesDao, MusicDao, GalleryDao, PointsDao, SystemDao, InfinityDao, VmDao, YoutubeDao],
)
class AppDatabase extends _$AppDatabase {
  static AppDatabase? _instance;

  static AppDatabase get instance {
    if (_instance == null) {
      throw Exception("AppDatabase has not been initialized yet!");
    }
    return _instance!;
  }

  AppDatabase(QueryExecutor e) : super(e) {
    _instance = this;
  }

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      beforeOpen: (details) async {
        await customStatement('PRAGMA journal_mode=WAL;');
        await customStatement('CREATE TABLE IF NOT EXISTS notes (id TEXT PRIMARY KEY, content TEXT, updated_at INTEGER, is_dirty INTEGER DEFAULT 0);');
        await customStatement('CREATE TABLE IF NOT EXISTS habits (id TEXT PRIMARY KEY, name TEXT, streak INTEGER DEFAULT 0, done INTEGER DEFAULT 0, is_dirty INTEGER DEFAULT 0);');
      },
    );
  }

  Stream<List<HabitData>> watchAllHabits() {
    return customSelect('SELECT * FROM habits ORDER BY id').watch().map((rows) {
      return rows.map((row) => HabitData.fromMap(row.data)).toList();
    });
  }
}
