import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:wireguard_flutter/wireguard_flutter.dart';
import 'package:permission_handler/permission_handler.dart';

class VpnManager {
  static final VpnManager instance = VpnManager._internal();
  VpnManager._internal();

  final _wireguard = WireGuardFlutter.instance;
  
  // Custom DDNS API created in Cloudflare Worker
  final String _customDdnsApiUrl = "https://your-worker-name.your-cloudflare-subdomain.workers.dev/get";
  
  // Hardcoded for local testing if API fails
  String _serverIp = "192.168.1.20";
  
  // The private and public keys generated by the Wireguard server
  String _privateKey = "";
  String _publicKey = "";
  
  Future<void> initialize() async {
    try {
      debugPrint("Initializing Custom VPN Manager...");
      await _wireguard.initialize(interfaceName: "wg0");
      
      if (Platform.isAndroid) {
        await Permission.notification.request();
      }

      await _fetchDynamicIp();
      await _setupAndConnect();
    } catch (e) {
      debugPrint("Failed to initialize VPN: $e");
    }
  }

  Future<void> _fetchDynamicIp() async {
    try {
      final client = HttpClient()..connectionTimeout = const Duration(seconds: 3);
      final req = await client.getUrl(Uri.parse(_customDdnsApiUrl));
      final res = await req.close();
      if (res.statusCode == 200) {
        final body = await res.transform(utf8.decoder).join();
        final data = jsonDecode(body);
        if (data['ip'] != null) {
          _serverIp = data['ip'];
          debugPrint("Fetched dynamic IP from Custom API: $_serverIp");
        }
      }
    } catch (e) {
      debugPrint("Could not fetch IP from Custom API, falling back to $_serverIp: $e");
    }
  }

  Future<void> _setupAndConnect() async {
    if (_privateKey.isEmpty || _publicKey.isEmpty) {
      debugPrint("VPN Keys not yet configured. Skipping auto-connect.");
      return;
    }

    try {
      await _wireguard.startVpn(
        serverAddress: "$_serverIp:51820",
        wgQuickConfig: """
[Interface]
PrivateKey = $_privateKey
Address = 10.13.13.2/32
DNS = 1.1.1.1

[Peer]
PublicKey = $_publicKey
AllowedIPs = 0.0.0.0/0
Endpoint = $_serverIp:51820
PersistentKeepalive = 25
""",
        providerBundleIdentifier: "com.lifeos.app.lifeos_client.vpn",
      );
      debugPrint("Connected to Wireguard VPN successfully.");
    } catch (e) {
      debugPrint("Failed to start VPN: $e");
    }
  }

  Future<void> disconnect() async {
    try {
      await _wireguard.stopVpn();
    } catch (e) {
      debugPrint("Failed to stop VPN: $e");
    }
  }
}
