import 'package:flutter/material.dart';
import 'app_skin.dart';

/// Centralized registry of all world-class built-in skins and palettes in LifeOS.
class AppSkinRegistry {
  static const AppSkin oled = AppSkin(
    id: 'oled',
    name: 'OLED Pure Black',
    description: 'True #000000 black with subtle dark charcoal surfaces and sleek monochrome silver/white accents.',
    brightness: Brightness.dark,
    tags: ['OLED', 'Dark', 'Monochrome'],
    bg0: Color(0xFF000000),
    bg1: Color(0xFF0C0C0C),
    bg2: Color(0xFF181818),
    fg: Color(0xFFEDEDED),
    textMuted: Color(0xFF7E7E7E),
    accent: Color(0xFFF5F5F5),
    accentSecondary: Color(0xFFCCCCCC),
    green: Color(0xFFE0E0E0),
    red: Color(0xFFE57373),
    yellow: Color(0xFFFFD54F),
    blue: Color(0xFFB0BEC5),
    purple: Color(0xFFB0BEC5),
    aqua: Color(0xFFCFD8DC),
    orange: Color(0xFFFFB74D),
    cyan: Color(0xFFCFD8DC),
    grey: Color(0xFF505050),
  );

  static const AppSkin everforest = AppSkin(
    id: 'everforest',
    name: 'Everforest Dark',
    description: 'Comfortable, earthy warm green sanctuary palette.',
    brightness: Brightness.dark,
    tags: ['Dark', 'Earthy', 'LifeOS Default'],
    bg0: Color(0xFF2D353B),
    bg1: Color(0xFF343F44),
    bg2: Color(0xFF3D484D),
    fg: Color(0xFFD3C6AA),
    textMuted: Color(0xFF859289),
    accent: Color(0xFFA7C080),
    accentSecondary: Color(0xFF7FBBB3),
    green: Color(0xFFA7C080),
    red: Color(0xFFE67E80),
    yellow: Color(0xFFDBBC7F),
    blue: Color(0xFF7FBBB3),
    purple: Color(0xFFD699B6),
    aqua: Color(0xFF83C092),
    orange: Color(0xFFE69875),
    cyan: Color(0xFF83C092),
    grey: Color(0xFF859289),
  );

  static const AppSkin catppuccinMocha = AppSkin(
    id: 'catppuccin_mocha',
    name: 'Catppuccin Mocha',
    description: 'The #1 Obsidian & developer community pastel dark palette.',
    brightness: Brightness.dark,
    tags: ['Dark', 'Pastel', 'Obsidian #1'],
    bg0: Color(0xFF1E1E2E),
    bg1: Color(0xFF181825),
    bg2: Color(0xFF313244),
    fg: Color(0xFFCDD6F4),
    textMuted: Color(0xFFA6ADC8),
    accent: Color(0xFFCBA6F7),
    accentSecondary: Color(0xFF89B4FA),
    green: Color(0xFFA6E3A1),
    red: Color(0xFFF38BA8),
    yellow: Color(0xFFF9E2AF),
    blue: Color(0xFF89B4FA),
    purple: Color(0xFFCBA6F7),
    aqua: Color(0xFF94E2D5),
    orange: Color(0xFFFAB387),
    cyan: Color(0xFF89DCEB),
    grey: Color(0xFF6C7086),
  );

  static const AppSkin catppuccinLatte = AppSkin(
    id: 'catppuccin_latte',
    name: 'Catppuccin Latte',
    description: 'Warm, cozy daylight pastel theme with soft contrasts.',
    brightness: Brightness.light,
    tags: ['Light', 'Pastel', 'Cozy'],
    bg0: Color(0xFFEFF1F5),
    bg1: Color(0xFFE6E9EF),
    bg2: Color(0xFFCCD0DA),
    fg: Color(0xFF4C4F69),
    textMuted: Color(0xFF6C6F85),
    accent: Color(0xFF8839EF),
    accentSecondary: Color(0xFF1E66F5),
    green: Color(0xFF40A02B),
    red: Color(0xFFD20F39),
    yellow: Color(0xFFDF8E1D),
    blue: Color(0xFF1E66F5),
    purple: Color(0xFF8839EF),
    aqua: Color(0xFF179299),
    orange: Color(0xFFFE640B),
    cyan: Color(0xFF04A5E5),
    grey: Color(0xFF9CA0B0),
  );

  static const AppSkin dracula = AppSkin(
    id: 'dracula',
    name: 'Dracula',
    description: 'Iconic dark vampire palette by Zeno Rocha with vibrant accents.',
    brightness: Brightness.dark,
    tags: ['Dark', 'Vibrant', 'Classic'],
    bg0: Color(0xFF282A36),
    bg1: Color(0xFF21222C),
    bg2: Color(0xFF44475A),
    fg: Color(0xFFF8F8F2),
    textMuted: Color(0xFF6272A4),
    accent: Color(0xFFBD93F9),
    accentSecondary: Color(0xFFFF79C6),
    green: Color(0xFF50FA7B),
    red: Color(0xFFFF5555),
    yellow: Color(0xFFF1FA8C),
    blue: Color(0xFF8BE9FD),
    purple: Color(0xFFBD93F9),
    aqua: Color(0xFF8BE9FD),
    orange: Color(0xFFFFB86C),
    cyan: Color(0xFF8BE9FD),
    grey: Color(0xFF6272A4),
  );

  static const AppSkin tokyoNight = AppSkin(
    id: 'tokyo_night',
    name: 'Tokyo Night',
    description: 'Neon metropolis accents against dark midnight skies.',
    brightness: Brightness.dark,
    tags: ['Dark', 'Neon', 'Modern'],
    bg0: Color(0xFF1A1B26),
    bg1: Color(0xFF16161E),
    bg2: Color(0xFF24283B),
    fg: Color(0xFFC0CAF5),
    textMuted: Color(0xFF565F89),
    accent: Color(0xFF7AA2F7),
    accentSecondary: Color(0xFFBB9AF7),
    green: Color(0xFF9ECE6A),
    red: Color(0xFFF7768E),
    yellow: Color(0xFFE0AF68),
    blue: Color(0xFF7AA2F7),
    purple: Color(0xFFBB9AF7),
    aqua: Color(0xFF7DCFFF),
    orange: Color(0xFFFF9E64),
    cyan: Color(0xFF7DCFFF),
    grey: Color(0xFF565F89),
  );

  static const AppSkin nord = AppSkin(
    id: 'nord',
    name: 'Nord',
    description: 'Arctic, north-bluish clean and elegant minimalist aesthetic.',
    brightness: Brightness.dark,
    tags: ['Dark', 'Minimal', 'Arctic'],
    bg0: Color(0xFF2E3440),
    bg1: Color(0xFF3B4252),
    bg2: Color(0xFF434C5E),
    fg: Color(0xFFECEFF4),
    textMuted: Color(0xFFD8DEE9),
    accent: Color(0xFF88C0D0),
    accentSecondary: Color(0xFF81A1C1),
    green: Color(0xFFA3BE8C),
    red: Color(0xFFBF616A),
    yellow: Color(0xFFEBCB8B),
    blue: Color(0xFF81A1C1),
    purple: Color(0xFFB48EAD),
    aqua: Color(0xFF8FBCBB),
    orange: Color(0xFFD08770),
    cyan: Color(0xFF88C0D0),
    grey: Color(0xFF4C566A),
  );

  static const AppSkin gruvboxDark = AppSkin(
    id: 'gruvbox_dark',
    name: 'Gruvbox Dark',
    description: 'Retro groove warm vintage palette crafted for long-session comfort.',
    brightness: Brightness.dark,
    tags: ['Dark', 'Retro', 'Warm'],
    bg0: Color(0xFF282828),
    bg1: Color(0xFF1D2021),
    bg2: Color(0xFF3C3836),
    fg: Color(0xFFEBDBB2),
    textMuted: Color(0xFFA89984),
    accent: Color(0xFFFABD2F),
    accentSecondary: Color(0xFFFE8019),
    green: Color(0xFFB8BB26),
    red: Color(0xFFFB4934),
    yellow: Color(0xFFFABD2F),
    blue: Color(0xFF83A598),
    purple: Color(0xFFD3869B),
    aqua: Color(0xFF8EC07C),
    orange: Color(0xFFFE8019),
    cyan: Color(0xFF8EC07C),
    grey: Color(0xFF928374),
  );

  static const AppSkin rosePine = AppSkin(
    id: 'rose_pine',
    name: 'Rosé Pine',
    description: 'Minimalist Soho vibes with pine, foam, gold and gentle rose.',
    brightness: Brightness.dark,
    tags: ['Dark', 'Aesthetic', 'Pastel'],
    bg0: Color(0xFF191724),
    bg1: Color(0xFF1F1D2E),
    bg2: Color(0xFF26233A),
    fg: Color(0xFFE0DEF4),
    textMuted: Color(0xFF908CAA),
    accent: Color(0xFFEB6F92),
    accentSecondary: Color(0xFF9CCFD8),
    green: Color(0xFF31748F),
    red: Color(0xFFEB6F92),
    yellow: Color(0xFFF6C177),
    blue: Color(0xFF9CCFD8),
    purple: Color(0xFFC4A7E7),
    aqua: Color(0xFF9CCFD8),
    orange: Color(0xFFEA9D34),
    cyan: Color(0xFF56949F),
    grey: Color(0xFF6E6A86),
  );

  static const AppSkin defaultDark = AppSkin(
    id: 'default_dark',
    name: 'Obsidian / GitHub Dark',
    description: 'Standard modern slate & charcoal clean dark mode.',
    brightness: Brightness.dark,
    tags: ['Dark', 'Standard', 'Clean'],
    bg0: Color(0xFF0D1117),
    bg1: Color(0xFF161B22),
    bg2: Color(0xFF30363D),
    fg: Color(0xFFC9D1D9),
    textMuted: Color(0xFF8B949E),
    accent: Color(0xFF58A6FF),
    accentSecondary: Color(0xFFBC8CFF),
    green: Color(0xFF3FB950),
    red: Color(0xFFF85149),
    yellow: Color(0xFFD29922),
    blue: Color(0xFF58A6FF),
    purple: Color(0xFFBC8CFF),
    aqua: Color(0xFF39C5BB),
    orange: Color(0xFFF0883E),
    cyan: Color(0xFF56D4DD),
    grey: Color(0xFF6E7681),
  );

  static const AppSkin defaultLight = AppSkin(
    id: 'default_light',
    name: 'Obsidian / GitHub Light',
    description: 'Crisp, bright daylight theme with clear contrast and legibility.',
    brightness: Brightness.light,
    tags: ['Light', 'Standard', 'Daylight'],
    bg0: Color(0xFFFFFFFF),
    bg1: Color(0xFFF6F8FA),
    bg2: Color(0xFFD0D7DE),
    fg: Color(0xFF1F2328),
    textMuted: Color(0xFF656D76),
    accent: Color(0xFF0969DA),
    accentSecondary: Color(0xFF8250DF),
    green: Color(0xFF1A7F37),
    red: Color(0xFFCF222E),
    yellow: Color(0xFF9A6700),
    blue: Color(0xFF0969DA),
    purple: Color(0xFF8250DF),
    aqua: Color(0xFF1B7C83),
    orange: Color(0xFFBC4C00),
    cyan: Color(0xFF057692),
    grey: Color(0xFF8C959F),
  );

  static const AppSkin solarizedLight = AppSkin(
    id: 'solarized_light',
    name: 'Solarized Light',
    description: 'Calibrated low-contrast light palette engineered for eye comfort.',
    brightness: Brightness.light,
    tags: ['Light', 'Solarized', 'Low Contrast'],
    bg0: Color(0xFFFDF6E3),
    bg1: Color(0xFFEEE8D5),
    bg2: Color(0xFFE0D8C3),
    fg: Color(0xFF657B83),
    textMuted: Color(0xFF93A1A1),
    accent: Color(0xFF268BD2),
    accentSecondary: Color(0xFF2AA198),
    green: Color(0xFF859900),
    red: Color(0xFFDC322F),
    yellow: Color(0xFFB58900),
    blue: Color(0xFF268BD2),
    purple: Color(0xFF6C71C4),
    aqua: Color(0xFF2AA198),
    orange: Color(0xFFCB4B16),
    cyan: Color(0xFF2AA198),
    grey: Color(0xFF839496),
  );

  static const AppSkin synthwave = AppSkin(
    id: 'synthwave',
    name: 'Synthwave \'84',
    description: 'Electric neon 80s cyberpunk theme with glowing magenta and cyan.',
    brightness: Brightness.dark,
    tags: ['Dark', 'Cyberpunk', 'Vibrant'],
    bg0: Color(0xFF262335),
    bg1: Color(0xFF241B2F),
    bg2: Color(0xFF34294F),
    fg: Color(0xFFFDFDFD),
    textMuted: Color(0xFF848BB2),
    accent: Color(0xFFFF7EDB),
    accentSecondary: Color(0xFF36F9F6),
    green: Color(0xFF72F1B8),
    red: Color(0xFFFE4450),
    yellow: Color(0xFFFEDE5D),
    blue: Color(0xFF03EDF9),
    purple: Color(0xFFB171FF),
    aqua: Color(0xFF36F9F6),
    orange: Color(0xFFFF8B39),
    cyan: Color(0xFF36F9F6),
    grey: Color(0xFF614D85),
  );

  static const List<AppSkin> allSkins = [
    oled,
    everforest,
    catppuccinMocha,
    dracula,
    tokyoNight,
    nord,
    gruvboxDark,
    rosePine,
    synthwave,
    defaultDark,
    defaultLight,
    catppuccinLatte,
    solarizedLight,
  ];

  static final Map<String, AppSkin> _lookup = {
    for (final s in allSkins) s.id: s,
  };

  /// Returns the matching skin by ID, safely defaulting to Everforest Dark if not found.
  static AppSkin getById(String? id) {
    if (id == null || id.isEmpty) return everforest;
    return _lookup[id] ?? everforest;
  }
}
